# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eucNorm <- function(x, d) {
    .Call(`_RPD_eucNorm`, x, d)
}

MAD <- function(x, med, n) {
    .Call(`_RPD_MAD`, x, med, n)
}

RPD_outl_C <- function(x, X, beta, quant, n, d, m, ndir, ndir2, Jmax, echo) {
    .Call(`_RPD_RPD_outl_C`, x, X, beta, quant, n, d, m, ndir, ndir2, Jmax, echo)
}

PP_PCA_C <- function(X, n, d, q, robust, eps, echo) {
    .Call(`_RPD_PP_PCA_C`, X, n, d, q, robust, eps, echo)
}

