# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eucNorm <- function(x, d) {
    .Call(`_RPD_eucNorm`, x, d)
}

MAD <- function(x, med, n) {
    .Call(`_RPD_MAD`, x, med, n)
}

RPD_outl_C <- function(x, X, alpha, beta, quant, gammas, basis, n, d, m, ngammas, ndir, ndir2, Jmax, echo) {
    .Call(`_RPD_RPD_outl_C`, x, X, alpha, beta, quant, gammas, basis, n, d, m, ngammas, ndir, ndir2, Jmax, echo)
}

